extends: airbnb-base
rules:
    indent:
    - error
    - 4
    linebreak-style:
    - error
    - unix
    quotes:
    - error
    - single
    semi:
    - error
    - always
    comma-dangle:
    - error
    - always-multiline
    no-cond-assign:
    - error
    - always
    max-len:
    - error
    no-restricted-syntax:
    - error
    - for-in
    - for
    - with
    - do
    no-iterator: 'off'
    no-continue: 'off'
    no-console: 'off'
    no-underscore-dangle: 'off'
    class-methods-use-this: 'off'
env:
    jasmine: true
    node: true

