language: node_js

node_js:
  - '8'

#matrix:
#  allow_failures:
#    - os: osx
#  include:
#    - os: linux
#      env: SKIP_E2E=false
#    - os: osx
#      env: SKIP_E2E=true

addons:
  apt:
    packages:
      - xvfb
      - xorriso
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar

env:
  global:
    - ELECTRON_ENABLE_LOGGING=1
    - USE_SYSTEM_XORRISO=true
    - TESTS_EXTRA_DELAY=true
    - TESTS_SKIP_UNRELIABLE=true

before_script:
  - npm run rebuild

cache:
  directories:
    - node_modules

script:
  - npm run test-v-headless
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make build-macos ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make build-linux ; fi
