language: node_js

node_js:
- '8'

addons:
  apt:
    packages:
      - xvfb

env:
    global:
        - ELECTRON_ENABLE_LOGGING=1

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm run rebuild
  - sleep 3 # give xvfb some time to start


cache:
  directories:
    - node_modules

script:
  - npm run test
