language: node_js

node_js:
  - '8'

#matrix:
#  allow_failures:
#    - os: osx
#  include:
#    - os: linux
#      env: SKIP_E2E=false
#    - os: osx
#      env: SKIP_E2E=true

addons:
  apt:
    packages:
      - xvfb
      - xorriso
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar

env:
  global:
    - ELECTRON_ENABLE_LOGGING=1
    - USE_SYSTEM_XORRISO=true
    - TESTS_EXTRA_DELAY=true
    - TESTS_SKIP_UNRELIABLE=true
    - BUILD_TARGET=build-linux
    - TEST_TARGET=test-v-headless

before_script:
  - npm run rebuild

cache:
  directories:
    - node_modules

script:
  - npm run $TEST_TARGET
  - make $BUILD_TARGET
