language: node_js

node_js:
- '8'

addons:
  apt:
    packages:
      - xvfb

env:
    global:
        - ELECTRON_ENABLE_LOGGING=1
        - USE_SYSTEM_XORRISO=true

before_script:
  - npm run rebuild

cache:
  directories:
    - node_modules

script:
  - npm run test-v-headless
  - ./node_modules/.bin/electron-builder --linux
