language: node_js

node_js:
- '8'

addons:
  apt:
    packages:
      - xvfb

env:
    global:
        - ELECTRON_ENABLE_LOGGING=1

#- "export DISPLAY=:99.0"
#- "sh -e /etc/init.d/xvfb start"
#- sleep 3 # give xvfb some time to start
before_script:
  - npm run rebuild


cache:
  directories:
    - node_modules

script:
  - npm run test-v-headless
