os: unstable
environment:
  GH_TOKEN:
    secure: LKhaInBDHQndUD6byBcUSXTC9uTMy2IMycazh/d7u5G8QcrX21E+C2SwMdWXVA2k
  matrix:
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - npm run test-v && exit 0 # Have it continue building even on non-zero
matrix:
  fast_finish: true
build: off
version: '0.0.14-{build}'
shallow_clone: true
clone_depth: 1

test_script:
  - ./node_modules/.bin/electron-builder --win --x64
